[book]
title = "balance.tf"
authors = ["TristenMilk", "rrredface"]
description = "A collection of ideas for balance changes in TF2"
src = "src"

[build]
build-dir = "docs"

[output.html]
additional-css = ["css/custom.css"]
